baseURL = "https://tjp.io/"
languageCode = "en-us"
title = "Travis Parker"
theme = "etch"
copyright = "Copyright 2020 Travis J Parker"

[params]
  copyright = "Copyright 2020 Travis J Parker"

[author]
  name = "Travis Parker"
