title = "Travis Parker"
baseURL = "https://tjp.io/"
languageCode = "en-us"
theme = "etch-tjp"
copyright = "Copyright 2020 Travis J Parker"

[params]
  copyright = "Copyright 2020 Travis J Parker"

[author]
  name = "Travis Parker"
