title = "Travis Parker"
baseURL = "https://tjp.io/"
languageCode = "en-us"
theme = "etch-tjp"
copyright = "Copyright © 2020 Travis J Parker"
rssLimit = 10
disableKinds = ["taxonomy", "term"]

[params]
  copyright = "Copyright © 2020 Travis J Parker"
  mainSections = ["posts"]

[author]
  name = "Travis Parker"

[markup.goldmark.renderer]
  unsafe = true
